# Number of olympics games have been held?
SELECT YEAR,CITY,SEASON
FROM ATHLETES;

# The total no of nations who participated in each olympics
SELECT GAMES,COUNT(DISTINCT(TEAM)) AS NUMBER_OF_NATIONS
FROM ATHLETES
GROUP BY GAMES
ORDER BY GAMES;

# Nations that have participated in most number of olympics
WITH TEMP AS (
    SELECT TEAM,COUNT(DISTINCT(GAMES)) AS TOTAL_GAMES
    FROM ATHLETES
    GROUP BY TEAM
)
SELECT TEAM
FROM TEMP
WHERE TOTAL_GAMES IN (SELECT MAX(TOTAL_GAMES) FROM TEMP);

# Sport that has been played in all summer olympics
WITH TEMP AS (
    SELECT SPORT,COUNT(DISTINCT(GAMES)) AS TOTAL_GAMES
    FROM ATHLETES
    WHERE SEASON = 'SUMMER'
    GROUP BY SPORT
)
SELECT SPORT 
FROM TEMP
WHERE TOTAL_GAMES = (SELECT MAX(TOTAL_GAMES) FROM TEMP);

# Olympics with maximum and minimum number of participating nations
SELECT GAMES,COUNT(DISTINCT(TEAM)) AS TOTAL_TEAMS,
RANK() OVER (ORDER BY COUNT(DISTINCT(TEAM))) AS LOWEST,
RANK() OVER (ORDER BY COUNT(DISTINCT(TEAM)) DESC) AS HIGHEST
FROM ATHLETES
GROUP BY GAMES
HAVING COUNT(DISTINCT TEAM) IN (
    SELECT MIN(TOTAL_TEAMS) 
    FROM (SELECT COUNT(DISTINCT TEAM) AS TOTAL_TEAMS FROM ATHLETES GROUP BY GAMES) AS TEMP
)
OR COUNT(DISTINCT TEAM) IN (
    SELECT MAX(TOTAL_TEAMS) 
    FROM (SELECT COUNT(DISTINCT TEAM) AS TOTAL_TEAMS FROM ATHLETES GROUP BY GAMES) AS TEMP
);

# Sex ratio in the olympics across years
SELECT DISTINCT(SELECT COUNT(SEX) FROM ATHLETES WHERE SEX = 'M') / 
(SELECT COUNT(SEX) FROM ATHLETES WHERE SEX = 'F')
AS MALE_FEMALE_RATIO
FROM ATHLETES;

# Oldest individual to have won a gold medal
SELECT * 
FROM ATHLETES
WHERE MEDAL = 'GOLD'
ORDER BY AGE DESC
LIMIT 1;

# Youngest individual to have won a gold medal
SELECT * 
FROM ATHLETES
WHERE MEDAL = 'GOLD'
ORDER BY AGE ASC
LIMIT 1;

# Top 5 athletes with most number of medals
SELECT NAME,COUNT(MEDAL) AS MEDAL_COUNT
FROM ATHLETES
WHERE MEDAL = 'GOLD'
GROUP BY NAME
ORDER BY MEDAL_COUNT DESC
LIMIT 5;

# Gold,silver,bronze medals won by each nation
SELECT TEAM,
COUNT(CASE WHEN MEDAL = 'GOLD' THEN 1 END) AS GOLD_COUNT,
COUNT(CASE WHEN MEDAL = 'SILVER' THEN 1 END) AS SILVER_COUNT,
COUNT(CASE WHEN MEDAL = 'BRONZE' THEN 1 END) AS BRONZE_COUNT
FROM ATHLETES
GROUP BY TEAM
ORDER BY GOLD_COUNT DESC;

# Maximum number of medals in each olympics
WITH TEMP AS (
SELECT GAMES,TEAM,
	COUNT(CASE WHEN MEDAL = 'GOLD' THEN 1 END) AS GOLD_COUNT,
	COUNT(CASE WHEN MEDAL = 'SILVER' THEN 1 END) AS SILVER_COUNT,
	COUNT(CASE WHEN MEDAL = 'BRONZE' THEN 1 END) AS BRONZE_COUNT
FROM ATHLETES 
WHERE MEDAL IN ('GOLD','SILVER','BRONZE')
GROUP BY TEAM 
ORDER BY GAMES
)
SELECT DISTINCT GAMES,MAX_GOLD,MAX_SILVER,MAX_BRONZE
FROM (
	SELECT GAMES,
	FIRST_VALUE(TEAM) OVER(PARTITION BY GAMES ORDER BY GOLD_COUNT) AS MAX_GOLD,
        FIRST_VALUE(TEAM) OVER(PARTITION BY GAMES ORDER BY SILVER_COUNT) AS MAX_SILVER,
        FIRST_VALUE(TEAM) OVER(PARTITION BY GAMES ORDER BY BRONZE_COUNT) AS MAX_BRONZE
	FROM TEMP
) X;

# Medals won by India
SELECT TEAM,SPORT,GAMES,COUNT(MEDAL) AS TOTAL_MEDALS
FROM ATHLETES
WHERE TEAM = 'INDIA'
GROUP BY TEAM,SPORT,GAMES;

# Nations that have never won a gold but have won either silver or bronze
SELECT TEAM FROM (
    SELECT TEAM,
    COUNT(CASE WHEN MEDAL = 'GOLD' THEN 1 END) AS GOLD_COUNT,
    COUNT(CASE WHEN MEDAL = 'SILVER' THEN 1 END) AS SILVER_COUNT,
    COUNT(CASE WHEN MEDAL = 'BRONZE' THEN 1 END) AS BRONZE_COUNT
    FROM ATHLETES
    WHERE MEDAL IN ('GOLD','SILVER','BRONZE')
    GROUP BY TEAM	
) TEMP
WHERE GOLD_COUNT = 0 AND SILVER_COUNT != 0 OR BRONZE_COUNT != 0;
